name: Push-Release-2022-07-To-Dockerhub

on:
  push:
    branches: [ release-2022-08 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.hub
          push: true
          tags: weilkiti/sysmlv2-jupyter:2022-08
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
